export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const SET_SEARCH_ORIGIN = "SET_SEARCH_ORIGIN";

export const GET_SEARCH_RESULT = "GET_SEARCH_RESULT";
export const GET_SEARCH_RESULT_SUCCEED = "GET_SEARCH_RESULT_SUCCEED";
export const GET_SEARCH_RESULT_FAIL = "GET_SEARCH_RESULT_FAIL";

export const GET_CONNECTED_ACCOUNT = "GET_CONNECTED_ACCOUNT";
export const GET_CONNECTED_ACCOUNT_SUCCEED = "GET_CONNECTED_ACCOUNT_SUCCEED";
export const GET_CONNECTED_ACCOUNT_FAIL = "GET_CONNECTED_ACCOUNT_FAIL";

export const SET_CONNECTED_ACCOUNTS = "SET_CONNECTED_ACCOUNTS";

export const SET_FIRSTCONNECT = "SET_FIRSTCONNECT";

export const SET_SIGNUPEMAIL = "SET_SIGNUPEMAIL";
export const SET_SIGNUPPASSWORD = "SET_SIGNUPPASSWORD";

export const SET_SHOWADDACCOUNT = "SET_SHOWADDACCOUNT";
