/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

import { userPoolID } from "./config";

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id: "us-east-1:209715472977",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_kylhAkCDK",
  aws_user_pools_web_client_id: userPoolID,
  oauth: {},
};

export default awsmobile;
