/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b5a42898-5d3b-4a81-be64-561a8524acd5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_tyFn8cNzi",
    "aws_user_pools_web_client_id": "6ao7melgeji0lih0pee05he0kj",
    "oauth": {}
};


export default awsmobile;
