/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

import { aws_user_pools_web_client_id,aws_cognito_identity_pool_id, aws_user_pools_id } from "./config";

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id: aws_cognito_identity_pool_id,
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: aws_user_pools_id,
  aws_user_pools_web_client_id: aws_user_pools_web_client_id,
  oauth: {},
};

export default awsmobile;
